import React from 'react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, act } from '@testing-library/react';
import StaticTruss from '../static/StaticTruss';
import StaticBeam from '../static/StaticBeam';
import { createStorageMock } from '../../tests/storageMock';
vi.mock('../../hooks/useAIEngine',()=>({useAIEngine:()=>({sync:vi.fn(),bubble:null,milestone:null})}));
vi.mock('../AITutor',()=>({default:()=>null}));
vi.mock('./ProgressBar',()=>({default:()=>null}));
beforeEach(() => vi.stubGlobal('localStorage', createStorageMock()));
afterEach(() => { cleanup(); vi.useRealTimers(); vi.unstubAllGlobals(); });
it('加载比例同步控制节点荷载、轴力与平衡表，固定终态色标，无虚构流点',()=>{
 const {container}=render(<StaticTruss/>);
 const cd=()=>container.querySelector('[data-flow-segment="CD"]');
 expect(Number(cd()?.getAttribute('data-flow-value'))).toBe(-37.5);
 fireEvent.change(screen.getByLabelText('加载比例'),{target:{value:'50'}});
 expect(Number(cd()?.getAttribute('data-flow-value'))).toBe(-18.75);
 expect(Number(cd()?.getAttribute('data-flow-ratio'))).toBeLessThanOrEqual(.5);
 expect(screen.getByLabelText('荷载 1 大小')).toHaveValue(50);
 expect(screen.getByRole('table',{name:'节点力分量'})).toHaveTextContent('−25');
 expect(container.querySelector('.force-flow-stream')).toBeNull();
 expect(container.querySelector('[data-flow-direction]')).toBeNull();
 fireEvent.change(screen.getByLabelText('荷载 1 方向'),{target:{value:'up'}});
 expect(screen.getByLabelText('加载比例')).toHaveValue('100');
 expect(Number(cd()?.getAttribute('data-flow-value'))).toBe(37.5);
 fireEvent.click(screen.getByRole('switch',{name:'显示内力色带'}));
 expect(container.querySelector('.force-flow-layer')).toBeNull();
 expect(screen.getByRole('table',{name:'节点力分量'})).toBeInTheDocument();
});
it('零比例没有残留色带，播放到满载停止，参数修改取消播放',()=>{
 vi.useFakeTimers();const {container}=render(<StaticBeam/>);
 fireEvent.click(screen.getByRole('button',{name:'播放加载演示'}));
 expect(screen.getByLabelText('加载比例')).toHaveValue('0');
 expect(container.querySelector('.force-flow-layer')).toBeNull();
 act(()=>vi.advanceTimersByTime(6000));
 expect(screen.getByLabelText('加载比例')).toHaveValue('100');
 expect(screen.getByRole('button',{name:'播放加载演示'})).toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'播放加载演示'}));
 fireEvent.change(screen.getByLabelText('荷载 1 大小'),{target:{value:'30'}});
 fireEvent.blur(screen.getByLabelText('荷载 1 大小'));
 expect(screen.getByLabelText('加载比例')).toHaveValue('100');
 expect(screen.getByRole('button',{name:'播放加载演示'})).toBeInTheDocument();
});
